// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using ImageMagick;
using Microsoft.Playwright;
//using OpenQA.Selenium;
//using OpenQA.Selenium.Chrome;
//using OpenQA.Selenium.Chromium;
//using OpenQA.Selenium.DevTools;
////using OpenQA.Selenium.DevTools.Page;
//using OpenQA.Selenium.Firefox;
//using OpenQA.Selenium.Remote;
//using OpenQA.Selenium.Support.UI;
//using OpenQA.Selenium.Interactions;
using Utf8Json;


namespace Argumentum.AssetConverter
{
    public class WebBasedGenerator
    {

        private Stopwatch sw;
        public WebBasedGeneratorConfig Config { get; set; }

        public WebBasedGenerator(WebBasedGeneratorConfig config, Stopwatch objSw)
        {
            Config = config;
            sw = objSw;

        }
     

        public void Run()
        {
            sw = Stopwatch.StartNew();
            //var harvestDictionary = HarvestImages();
            var harvestDictionary = Task.Run(async () => await HarvestImages()).Result; 
            var docImages = GenerateDocumentImages(harvestDictionary);
            
            GenerateDocuments(docImages);
            //Console.WriteLine($"Generation finished. Total duration: {sw.Elapsed}");

        }


        async Task<Dictionary<string, CardSetHarvest>>  HarvestImages()
        {

            Dictionary<string, CardSetHarvest> harvestDictionary;
            //var jsonHarvestName = Path.Combine(Environment.CurrentDirectory, "harvest.json");
            //if (File.Exists(jsonHarvestName))
            //{
            //    using var configStream = File.OpenRead(jsonHarvestName);
            //    harvestDictionary = JsonSerializer.Deserialize<Dictionary<string, CardSetHarvest>>(configStream);
            //    Console.WriteLine($"Loaded Harvest {jsonHarvestName}");
            //}
            //else
            //{

            harvestDictionary = new Dictionary<string, CardSetHarvest>();
            foreach (var configCardSet in Config.CardSets)
            {

                var jsonHarvestName = configCardSet.GetHarvestSerializationName(Config);
                if (File.Exists(jsonHarvestName))
                {
                    using var configStream = File.OpenRead(jsonHarvestName);
                    var currentHarvest = JsonSerializer.Deserialize<CardSetHarvest>(configStream);
                    Console.WriteLine($"Loaded Harvest {jsonHarvestName}: {sw.Elapsed}");
                    harvestDictionary[configCardSet.Name] = currentHarvest;
                }

            }

            if (harvestDictionary.Count < Config.CardSets.Count)
            {
                //var options = new ChromeOptions();
                //options.BinaryLocation = Config.ChromeBinaryPath;

                var exitCode = Microsoft.Playwright.Program.Main(new[] { "install" });
                if (exitCode != 0)
                {
                    throw new Exception($"Playwright exited with code {exitCode}");
                }

                using var playwright = await Playwright.CreateAsync();
                await using var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
                {
                    Headless = false,
                    //SlowMo = 50,
                });

                //using (var driver = new ChromeDriver(options))
                //{
                    try
                    {
                        //driver.Manage().Window.Minimize();
                        ////js = (IJavaScriptExecutor)driver;
                        ////vars = new Dictionary<String, Object>();
                        //driver.Navigate().GoToUrl(Config.CardpenUrl);
                        //driver.FindElement(By.Id("eg")).Click();


                        var page = await browser.NewPageAsync();
                        await page.GotoAsync(Config.CardpenUrl);




                    Thread.Sleep(TimeSpan.FromSeconds(5));

                        foreach (var configCardSet in Config.CardSets)
                        {
                            if (!harvestDictionary.ContainsKey(configCardSet.Name))
                            {
                                var currentHarvest = new CardSetHarvest();
                                var faces = await GenerateImages(page, configCardSet.FaceCardSetInfo, configCardSet.PauseFaceForEdits);
                                currentHarvest.Faces = faces;
                                if (configCardSet.BackCardSetInfo.IsSet)
                                {
                                    var backs = await GenerateImages(page, configCardSet.BackCardSetInfo, configCardSet.PauseBackForEdits);
                                    currentHarvest.Backs = backs;
                                }

                                var jsonHarvestName = configCardSet.GetHarvestSerializationName(Config);
                                var strNewConfig = JsonSerializer.PrettyPrint(JsonSerializer.ToJsonString(currentHarvest));
                                File.WriteAllText(jsonHarvestName, strNewConfig);
                                Console.WriteLine($"Serialized Harvest {jsonHarvestName}: {sw.Elapsed}");


                                harvestDictionary[configCardSet.Name] = currentHarvest;
                            }


                        }
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine(e);
                        throw;
                    }
                    //finally
                    //{
                    //    driver.Quit();
                    //}
                //}
            }




            //var strNewConfig = JsonSerializer.PrettyPrint(JsonSerializer.ToJsonString(harvestDictionary));
            //File.WriteAllText(jsonHarvestName, strNewConfig);
            //Console.WriteLine($"Serialized Harvest {jsonHarvestName}");
            //}

            return harvestDictionary;
        }



        Dictionary<DocumentConfig, List<CardImages>> GenerateDocumentImages(Dictionary<string, CardSetHarvest> harvestDictionary)
        {
            Dictionary<DocumentConfig, List<CardImages>> toReturn = new Dictionary<DocumentConfig, List<CardImages>>();

            foreach (var configDocument in Config.Documents)
            {
                List<CardImages> targetList;

                if (!toReturn.TryGetValue(configDocument, out targetList))
                {
                    targetList = new List<CardImages>();
                    toReturn[configDocument] = targetList;
                }

                foreach (var configCardSet in configDocument.CardSets)
                {
                    Console.WriteLine($"Generating card set images for {configDocument.DocumentName} - {configCardSet.CardSetName}: {sw.Elapsed}");



                    var currentHarvest = harvestDictionary[configCardSet.CardSetName];
                    var backImages = new Dictionary<string, MagickImage>();
                    if (currentHarvest.Backs != null)
                    {
                        foreach (var currentHarvestBack in currentHarvest.Backs.Images)
                        {
                            var backName = $"{currentHarvestBack.Key.ToLowerInvariant()}" ;
                            var backImageUrl = currentHarvestBack.Value;
                            var backImage = configCardSet.LoadAndProcessImageUrl(Config, configDocument,  backName, backImageUrl, currentHarvest.Backs.Dpi);
                            if (backName.Contains('-'))
                            {
                                backName = backName.Substring(backName.LastIndexOf('-'));
                            }

                            backImages[backName] = backImage;
                        }
                    }

                    
                    for (int i = 0; i < configCardSet.NbCopies; i++)
                    {
                        CardImages currentCard = null;
                        foreach (var currentHarvestFace in currentHarvest.Faces.Images)
                        {
                            var faceName = $"face_{currentHarvestFace.Key.ToLowerInvariant()}";
                            var faceImageUrl = currentHarvestFace.Value;
                            var faceImage = configCardSet.LoadAndProcessImageUrl(Config, configDocument, faceName, faceImageUrl, currentHarvest.Faces.Dpi);
                            if (currentCard == null)
                            {
                                currentCard = new CardImages();
                                targetList.Add(currentCard);
                                //currentCard.Front = new MagickImage(faceImage);
                                currentCard.Front = faceImage;
                            }
                            else
                            {
                                //currentCard.Back = new MagickImage(faceImage);
                                currentCard.Back = faceImage;
                                currentCard = null;
                            }
                            
                            if (backImages.Count > 0)
                            {
                                if (backImages.Count == 1)
                                {
                                    //currentCard.Back = new MagickImage(backImages.Values.First());
                                    currentCard.Back = backImages.Values.First();
                                }
                                else
                                {

                                    var targetBackName = backImages.Keys.First(bn => faceName.Contains(bn));
                                    //currentCard.Back = new MagickImage(backImages[targetBackName]);
                                    currentCard.Back = backImages[targetBackName];
                                }
                                currentCard = null;
                            }
                        }
                    }
                }



            }



            return toReturn;
        }


        private void GenerateDocuments(Dictionary<DocumentConfig, List<CardImages>> docImages)
        {
            Console.WriteLine($"Generation pdf documents: {sw.Elapsed}");
            var pdfDirectory = Config.GetPdfsDirectory();

            foreach (var docImageList in docImages)
            {
                var densityDirectory = Path.Combine(pdfDirectory, $@".\density-{docImageList.Key.TargetDensity}\");
                if (!Directory.Exists(densityDirectory))
                {
                    Directory.CreateDirectory(densityDirectory);
                }

                var targetFiles = new List<(string fileName, MagickImageCollection documentImages)>();
                MagickImageCollection collec;
                switch (docImageList.Key.DocumentFormat)
                {
                    case CardDocumentFormat.AlternateFaceAndBack:
                        collec = new MagickImageCollection(docImageList.Value.SelectMany(s =>
                        {
                            return new[] { s.Front, s.Back };
                        }));
                        var targetFile = Path.Combine(densityDirectory, docImageList.Key.DocumentName);
                        targetFiles.Add((targetFile, collec));
                        break;
                    case CardDocumentFormat.BackFirstOneDocPerBack:
                        var baseName = Path.Combine(densityDirectory, docImageList.Key.DocumentName);
                        var indexInsert = baseName.LastIndexOf('.');
                        var cardsPerBack = docImageList.Value.GroupBy(card => card.Back).ToArray();
                        for (int backIndex = 0; backIndex < cardsPerBack.Count(); backIndex++)
                        {
                            var frontsAndBack = cardsPerBack[backIndex];
                            var backThenFronts = new[] { frontsAndBack.Key }.Concat(frontsAndBack.Select(card => card.Front));
                            collec = new MagickImageCollection(backThenFronts);
                            var newName = $"{baseName.Substring(0, indexInsert)}-{backIndex+1}{baseName.Substring(indexInsert)}";
                            targetFiles.Add((newName,collec));
                        }
                       
                        break;
                    default:
                        throw new ArgumentOutOfRangeException();
                }

                foreach (var targetFile in targetFiles)
                {
                    targetFile.documentImages.Write(targetFile.fileName);
                    Console.WriteLine($"Generated pdf document {targetFile.fileName}: {sw.Elapsed}");
                }
               
                
            }
        }



      

        //private List<ImageMagick.MagickImage> GenerateImages(string exampleName)
        private async Task<CardPenHarvest> GenerateImages(IPage driver, CardSetInfo cardSet,
            bool pauseForEdits)
        {
            var toReturn = new CardPenHarvest();

            

            switch (cardSet.CardSetType)
            {
                case CardSetType.ExampleByName:
                    //driver.FindElement(By.Id("exampleList")).Click();
                    //var playwright = Task.Run(async () => await Playwright.CreateAsync()).Result ;
                    
                    //var dropdown = driver.FindElement(By.Id("exampleList"));
                    var dropdown = driver.Locator("#exampleList");
                    if (!await dropdown.IsVisibleAsync())
                    {
                        var exampleButton = driver.Locator("#eg");
                        await exampleButton.ClickAsync();
                        //Thread.Sleep(TimeSpan.FromSeconds(5));
                    }

                    await dropdown.ClickAsync();
                    Console.WriteLine($"Generating example {cardSet.ExampleName}: {sw.Elapsed}");
                    //dropdown.FindElement(By.XPath($"//option[. = '{cardSet.ExampleName}']")).Click();
                    await dropdown.SelectOptionAsync(cardSet.ExampleName);
                    //Thread.Sleep(TimeSpan.FromSeconds(5));
                    break;
                case CardSetType.CustomJson:
                    //driver.FindElement(By.Id("load")).Click();
                    //var importInput= driver.FindElement(By.Id("import"));
                    var importInput = driver.Locator("#import");
                    if (!await importInput.IsVisibleAsync())
                    {
                        var exampleButton = driver.Locator("#load");
                        await exampleButton.ClickAsync();
                        Thread.Sleep(TimeSpan.FromSeconds(2));
                    }
                    
                    var customFilePath = cardSet.CustomJsonFileName;
                    if (!Path.IsPathFullyQualified(cardSet.CustomJsonFileName))
                    {
                        customFilePath = Path.Combine(Environment.CurrentDirectory, customFilePath);
                    }
                    Console.WriteLine($"Generating CardSet {customFilePath}: {sw.Elapsed}");
                    await driver.SetInputFilesAsync("#import", customFilePath);
                    Thread.Sleep(TimeSpan.FromSeconds(5));



                    break;
                default:
                    throw new ArgumentOutOfRangeException();
            }

           
            if (pauseForEdits)
            {
                Console.WriteLine($"Chrome est en pause le temps de faire vos éditions.\n Appuyez sur une touche pour démarrer la génération");
                Console.Read();
            }
            //var objIFrame = driver.FindElement(By.Id("cpOutput"));
            var objIFrame = driver.FrameLocator("#cpOutput");


            //var objSession = ((ChromiumDriver) driver).CreateDevToolsSession();


            //driver.SwitchTo().Frame(objIFrame);
            //Console.WriteLine($"Waiting for html display {sw.Elapsed}");

            //new WebDriverWait(driver, TimeSpan.FromSeconds(20)).Until(drv => drv.FindElement(By.TagName("card")));
            var objCardTag = objIFrame.Locator("card");
            //await objCardTag.WaitForAsync(new LocatorWaitForOptions(){State = WaitForSelectorState.Attached});
            while (await objCardTag.CountAsync()==0)
            {
                Thread.Sleep(100);
            }


            //driver.SwitchTo().ParentFrame();

            
            //driver.FindElement(By.CssSelector(".image")).Click();
            await driver.Locator(".image").ClickAsync();

            Thread.Sleep(TimeSpan.FromSeconds(5));

            //objIFrame = new WebDriverWait(driver, TimeSpan.FromSeconds(20)).Until(drv => drv.FindElement(By.Id("cpOutput")));
            //driver.SwitchTo().Frame(objIFrame);
            Console.WriteLine($"Waiting for image display {sw.Elapsed}");
            //new WebDriverWait(driver, TimeSpan.FromSeconds(20)).Until(drv => drv.FindElement(By.TagName("card")));
            //await objCardTag.WaitForAsync(new LocatorWaitForOptions() { State = WaitForSelectorState.Attached });
            while (await objCardTag.CountAsync() == 0)
            {
                Thread.Sleep(100);
            }

            //var dpi = (long)driver.ExecuteScript("return dpi;");
            //var dpi = await driver.EvaluateAsync("return dpi;");
            //var dpi = await driver.EvaluateAsync("dpi");

            var dpi = await driver.Locator("#dpi").InputValueAsync();


            toReturn.Dpi = Convert.ToInt32(dpi);

            //Func<IWebDriver, IWebElement> generateButtonLambda = (IWebDriver drv) => drv.FindElement(By.Id("generateButton"));
            //var generateButton = new WebDriverWait(driver, TimeSpan.FromSeconds(5)).Until(drv => generateButtonLambda(drv));
            var objGenerateButton = objIFrame.Locator("#generateButton");
            await objGenerateButton.WaitForAsync(new LocatorWaitForOptions() { State = WaitForSelectorState.Attached });



            //var zipButtoLambda = new Func<IWebDriver, IWebElement>((IWebDriver drv) => drv.FindElement(By.Id("zipButton")));

            Thread.Sleep(TimeSpan.FromSeconds(1));

            //var zipButton = zipButtoLambda(driver);
            var zipButton = objIFrame.Locator("#zipButton"); ;
            
            Thread.Sleep(TimeSpan.FromSeconds(5));
            //generateButton.Click();
            await objGenerateButton.ClickAsync();
            //Console.WriteLine($"Waiting for Generated images  {sw.Elapsed}");
            //new WebDriverWait(driver, TimeSpan.FromSeconds(600)).Until(drv => zipButtoLambda(drv).Displayed && zipButtoLambda(drv).Enabled);

            await zipButton.WaitForAsync(new LocatorWaitForOptions() { State = WaitForSelectorState.Attached  });
            await zipButton.WaitForAsync(new LocatorWaitForOptions() { State = WaitForSelectorState.Visible,Timeout = 0 });
            var zipHandler = await zipButton.ElementHandleAsync();
            await zipHandler.WaitForElementStateAsync(ElementState.Enabled);

            //Console.WriteLine($"images generated {sw.Elapsed}");
            //var generatedImagesDiv = driver.FindElement(By.Id("cpImages"));
            var generatedImagesDiv = objIFrame.Locator("#cpImages");

            //var generatedImages = generatedImagesDiv.FindElements(By.TagName("img"));
            var generatedImages = generatedImagesDiv.Locator("img");

            var cardNames = new List<string>();

            //var cardsHtml = driver.FindElements(By.TagName("card"));
            var cardsHtml = objIFrame.Locator("card");
            for (var idxCard = 0; idxCard < await cardsHtml.CountAsync(); idxCard++)
            {
                var strCardName = idxCard.ToString(CultureInfo.InvariantCulture).PadLeft(3, '0');
                //var cardElement = cardsHtml[idxCard];
                var cardElement = cardsHtml.Nth(idxCard);
                //var cardCssName = cardElement.FindElements(By.ClassName("cardName"));
                var cardCssName = cardElement.Locator(".cardName");
                //if (cardCssName.Count > 0)
                if (await cardCssName.CountAsync() > 0)
                {
                    //strCardName = cardCssName[0].GetAttribute("textContent").Trim('-');
                    var currentCard = cardCssName.Nth(0);
                    //strCardName = (await currentCard.GetAttributeAsync("textContent"))?.Trim('-');
                    strCardName = (await currentCard.TextContentAsync())?.Trim('-');
                }
                cardNames.Add(strCardName);
            }

            if (await generatedImages.CountAsync() != cardNames.Count)
            {
                throw new ApplicationException("not same number of generated cards and card names");
            }

            for (int i = 0; i < await generatedImages.CountAsync(); i++)
            {
                //toReturn.Images[cardNames[i]] = generatedImages[i].GetAttribute("src");
                var currentGeneratedImage = generatedImages.Nth(i);
                var currentCardName = cardNames[i];
                toReturn.Images[currentCardName] = await currentGeneratedImage.GetAttributeAsync("src");
            }

            //driver.SwitchTo().ParentFrame();

            return toReturn;
        }



    }


    public class CardImages
    {
        public MagickImage Front { get; set; }

        public MagickImage Back { get; set; }

    }


}


