//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Argumentum.AssetConverter.DatasetUpdater {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Argumentum.AssetConverter.DatasetUpdater.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pk;path;depth;decimal_path_padded;family_fr;subfamily_fr;subsubfamily_fr;title_fr;description_fr;link_fr;family_fr_camelcase;depth_max4;card;remark_fr
        ///0;0;0;0.0000000;Arguments vertueux;;;Arguments vertueux;Arguments bien construits, clairs et pertinents;;argumentsVertueux;0;1;La production d&apos;une argumentation vertueuse implique de respecter une rigueur et des principes éthiques et intellectuels
        ///1;1;1;1.0000000;Argument pertinent;;;Argument pertinent;Argument correctement formulé et recevable;;argumentPer [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string CsvPromptSampleAssistant {
            get {
                return ResourceManager.GetString("CsvPromptSampleAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pk;path;depth;decimal_path_padded;family_fr;subfamily_fr;subsubfamily_fr;title_fr;description_fr;link_fr;family_fr_camelcase;depth_max4;card;remark_fr
        ///0;0;0;0.0000000;Arguments vertueux;;;Arguments vertueux;;;argumentsVertueux;0;1;
        ///1;1;1;1.0000000;Argument pertinent;;;Argument pertinent;;;argumentPertinent;1;1;
        ///2;1.1;2;1.1000000;Argument pertinent;Argument fondé;;Argument fondé;;;argumentPertinent;2;1;
        ///4;1.1.1.1;4;1.1110000;Argument pertinent;Argument fondé;Argument réel;Argument déductif;;;argumentPert [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string CsvPromptSampleUser {
            get {
                return ResourceManager.GetString("CsvPromptSampleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous incarnez un éditeur de CSV hautement compétent, dont la mission consiste à corriger et compléter les champs vides d&apos;un document CSV. Le document à modifier a été divisé en portions de lignes de CSV qui vous sont soumises sous forme de prompts d&apos;utilisateur. Votre réponse doit contenir les mêmes lignes, mais remplies et corrigées.
        ///
        ///Le fichier CSV à mettre à jour contient des lignes d&apos;une taxonomie d&apos;arguments vertueux en français. Ce travail vise à contrer une taxonomie de sophismes. Les deux taxonomi [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string CsvPromptSystem {
            get {
                return ResourceManager.GetString("CsvPromptSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [
        ///	{
        ///		&quot;path&quot;: &quot;4.3.3.1.2.1.1&quot;,
        ///		&quot;family_fr&quot;: &quot;Raisonnement valide&quot;,
        ///		&quot;subfamily_fr&quot;: &quot;Déductions correctes&quot;,
        ///		&quot;subsubfamily_fr&quot;: &quot;Raisonnement concluant&quot;,
        ///		&quot;title_fr&quot;: &quot;Syllogisme Barbara&quot;,
        ///		&quot;description_fr&quot;: &quot;Syllogisme de mode parfait où le terme moyen est un sujet dans la première prémisse et un prédicat dans la seconde prémisse&quot;,
        ///		&quot;remark_fr&quot;: &quot;Syllogisme du type Tout M est P, or tout S est M, donc tout S est P. Exemple: Tous les félidés sont sympathiques, Tous les chats sont des félidés, [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string FallaciesJsonPromptSampleAssistant {
            get {
                return ResourceManager.GetString("FallaciesJsonPromptSampleAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [
        ///	{
        ///		&quot;path&quot;: &quot;4.3.3.1.2.1.1&quot;,
        ///		&quot;family_fr&quot;: &quot;Raisonnement valide&quot;,
        ///		&quot;subfamily_fr&quot;: &quot;Déductions correctes&quot;,
        ///		&quot;subsubfamily_fr&quot;: &quot;Raisonnement concluant&quot;,
        ///		&quot;title_fr&quot;: &quot;Sylogisme Babara&quot;,
        ///		&quot;description_fr&quot;: &quot;Le syllogisme Barbara est un syllogisme de mode parfait&quot;,
        ///		&quot;remark_fr&quot;: &quot;Le syllogisme Barbara est un exemple de syllogisme de mode parfait qui présente une structure de raisonnement concluant particulièrement forte.&quot;,
        ///		&quot;link_fr&quot;: &quot;&quot;
        ///	},
        ///	{
        ///		&quot;path&quot;: &quot;1.1&quot;,
        ///		&quot;family_fr&quot;: &quot;Argument  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string FallaciesJsonPromptSampleUser {
            get {
                return ResourceManager.GetString("FallaciesJsonPromptSampleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous incarnez un éditeur de Json hautement compétent, dont la mission consiste à corriger les champs d&apos;un document Json. Le document à modifier a été divisé en portions de Json qui vous sont soumises sous forme de prompts d&apos;utilisateur. Votre réponse doit contenir la même structure, mais avec les champs corrigés.
        ///
        ///Le fichier Json à mettre à jour contient des éléments d&apos;une taxonomie d&apos;arguments vertueux en français. Ce travail vise à contrer une taxonomie de sophismes. Les deux taxonomies utilisent des te [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string FallaciesJsonPromptSystem {
            get {
                return ResourceManager.GetString("FallaciesJsonPromptSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [
        ///	{
        ///		&quot;path&quot;: &quot;4.3.3.1.2.1.1&quot;,
        ///		&quot;family_fr&quot;: &quot;Raisonnement valide&quot;,
        ///		&quot;subfamily_fr&quot;: &quot;Déductions correctes&quot;,
        ///		&quot;subsubfamily_fr&quot;: &quot;Raisonnement concluant&quot;,
        ///		&quot;title_fr&quot;: &quot;Syllogisme Barbara&quot;,
        ///		&quot;description_fr&quot;: &quot;Syllogisme de mode parfait où le terme moyen est un sujet dans la première prémisse et un prédicat dans la seconde prémisse&quot;,
        ///		&quot;remark_fr&quot;: &quot;Syllogisme du type Tout M est P, or tout S est M, donc tout S est P. Exemple: Tous les félidés sont sympathiques, Tous les chats sont des félidés, [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string VirtuesJsonPromptSampleAssistant {
            get {
                return ResourceManager.GetString("VirtuesJsonPromptSampleAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [
        ///	{
        ///		&quot;path&quot;: &quot;4.3.3.1.2.1.1&quot;,
        ///		&quot;family_fr&quot;: &quot;Raisonnement valide&quot;,
        ///		&quot;subfamily_fr&quot;: &quot;Déductions correctes&quot;,
        ///		&quot;subsubfamily_fr&quot;: &quot;Raisonnement concluant&quot;,
        ///		&quot;title_fr&quot;: &quot;Sylogisme Babara&quot;,
        ///		&quot;description_fr&quot;: &quot;Le syllogisme Barbara est un syllogisme de mode parfait&quot;,
        ///		&quot;remark_fr&quot;: &quot;Le syllogisme Barbara est un exemple de syllogisme de mode parfait qui présente une structure de raisonnement concluant particulièrement forte.&quot;,
        ///		&quot;link_fr&quot;: &quot;&quot;
        ///	},
        ///	{
        ///		&quot;path&quot;: &quot;1.1&quot;,
        ///		&quot;family_fr&quot;: &quot;Argument  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string VirtuesJsonPromptSampleUser {
            get {
                return ResourceManager.GetString("VirtuesJsonPromptSampleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous incarnez un éditeur de Json hautement compétent, dont la mission consiste à corriger les champs d&apos;un document Json. Le document à modifier a été divisé en portions de Json qui vous sont soumises sous forme de prompts d&apos;utilisateur. Votre réponse doit contenir la même structure, mais avec les champs corrigés.
        ///
        ///Le fichier Json à mettre à jour contient des éléments d&apos;une taxonomie d&apos;arguments vertueux en français. Ce travail vise à contrer une taxonomie de sophismes. Les deux taxonomies utilisent des te [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string VirtuesJsonPromptSystem {
            get {
                return ResourceManager.GetString("VirtuesJsonPromptSystem", resourceCulture);
            }
        }
    }
}
