<#
.SYNOPSIS
    Build/verify the v2.0.0 PDF bundle manifest (read-only on the bundle; writes only the manifest file).

.DESCRIPTION
    Validates that a release bundle directory contains the expected 8 languages x 10 PDF types
    (80 PDFs), computes size and (optionally) sha256 per file, and emits a markdown manifest
    (manifest-v2.0.0.md) with the inventory table, the eight A0 posters section and provenance.

    The script NEVER mutates the bundle: it only reads it and writes the manifest file at
    -ManifestPath. Fail-loud: any missing/unexpected file raises a non-zero exit code and the
    missing list is printed.

.PARAMETER BundleDir
    Root of the bundle to inventory. Default: the 06/09 bundle on the Drive mount.

.PARAMETER ManifestPath
    Where to write the manifest. Default: <BundleDir>\manifest-v2.0.0.md.

.PARAMETER SkipHashes
    Skip sha256 computation (useful on slow/network mounts). Sizes are always computed.
    The manifest then carries 'n/a' hashes and is marked HASH-IMPERFECT.

.PARAMETER StaleNote
    Optional markdown note (single line) appended verbatim to the manifest header, used to
    record a known staleness delta of the bundle vs the current master.

.PARAMETER BaseCommit
    Provenance commit that generated the bundle (default 2a2e7b32 = run E base).

.EXAMPLE
    .\package-v2.0.0.ps1 -SkipHashes   # fast size-only inventory on the Drive mount
    .\package-v2.0.0.ps1 -ManifestPath C:\Users\jsboi\AppData\Local\Temp\manifest-preview.md
#>
[CmdletBinding()]
param(
    [string]$BundleDir   = "G:\Mon Drive\Argumentum\review-v2.0.0-regen-20260906",
    [string]$ManifestPath = "",
    [switch]$SkipHashes  = $false,
    [string]$StaleNote   = "",
    [string]$BaseCommit  = "2a2e7b32"
)

$ErrorActionPreference = 'Stop'
$langs = @('ar','en','es','fa','fr','pt','ru','zh')
$types = @(
    'TarotCards',
    'TarotCards_Virtues',
    'PokerCards',
    'TarotCards_Print&Play_A4',
    'TarotCards_Print&Play_Light_A4',
    'PokerCards_Print&Play_A4',
    'PokerCards_Print&Play_Light_A4',
    'Fallacies_Web_A0',
    'Fallacies_Web_A4',
    'Fallacies_Web_Thumbnails_A4'
)

if (-not (Test-Path $BundleDir)) { Write-Error "BundleDir not found: $BundleDir"; exit 2 }
if (-not $ManifestPath) { $ManifestPath = Join-Path $BundleDir 'manifest-v2.0.0.md' }

$missing = @()
$inventory = [ordered]@{}
foreach ($l in $langs) {
    $langDir = Join-Path $BundleDir $l
    if (-not (Test-Path $langDir)) { $missing += "dir $l"; continue }
    foreach ($t in $types) {
        $file = Join-Path $langDir "Argumentum_$t`_$l.pdf"
        if (-not (Test-Path $file)) { $missing += "$l/$t"; continue }
        $f = Get-Item $file
        $hash = 'n/a'
        if (-not $SkipHashes) { $hash = (Get-FileHash $file -Algorithm SHA256).Hash }
        $inventory["$l/$t"] = [pscustomobject]@{ Lang=$l; Type=$t; Size=$f.Length; Hash=$hash }
    }
}

$expected = $langs.Count * $types.Count
$found = $inventory.Count
Write-Host "[package-v2.0.0] files: $found / $expected"
if ($missing.Count -gt 0) {
    Write-Host "[package-v2.0.0] MISSING $($missing.Count): $($missing -join ', ')"
    exit 1
}

# ---- render manifest ----
$total = ($inventory.Values | Measure-Object -Property Size -Sum).Sum
$rank = 0
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("# Manifest — v2.0.0 bundle (generated by docs/release-dossier/package-v2.0.0.ps1)")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("- **Generated**: $((Get-Date -Format 'yyyy-MM-dd HH:mm:ss'))")
[void]$sb.AppendLine("- **BundleDir**: $BundleDir")
[void]$sb.AppendLine("- **Base commit (provenance)**: $BaseCommit")
[void]$sb.AppendLine("- **Files**: $found / $expected (8 langs x 10 types) · **Total size**: $([math]::Round($total/1MB,1)) Mo")
[void]$sb.AppendLine("- **Hashes**: $(if ($SkipHashes) {'n/a (HASH-IMPERFECT — run without -SkipHashes for the final pass)'} else {'sha256 per file'})")
if ($StaleNote) { [void]$sb.AppendLine("- **Staleness delta**: $StaleNote") }
[void]$sb.AppendLine("")
[void]$sb.AppendLine("## Affiches A0 (explicit part of the release material)")
[void]$sb.AppendLine("| Fichier | Taille | sha256 |")
[void]$sb.AppendLine("|---|---|---|")
foreach ($l in $langs) {
    $k = "$l/Fallacies_Web_A0"
    $it = $inventory[$k]
    if (-not $it) { continue }
    $short = if ($it.Hash -ne 'n/a') { $it.Hash.Substring(0,16) + '…' } else { 'n/a' }
    [void]$sb.AppendLine("| Argumentum_Fallacies_Web_A0_$l.pdf | $([math]::Round($it.Size/1KB,1)) Ko | $short |")
}
[void]$sb.AppendLine("")
[void]$sb.AppendLine("## Inventaire langue x type (taille en Mo)")
[void]$sb.AppendLine("| | $($langs -join ' | ') | Total |")
[void]$sb.AppendLine(("|---" * ($langs.Count + 2)) + "|")
foreach ($t in $types) {
    $row = @($t)
    $sum = 0
    foreach ($l in $langs) {
        $it = $inventory["$l/$t"]
        if ($it) { $sum += $it.Size; $row += [math]::Round($it.Size/1MB,1) } else { $row += '-' }
    }
    [void]$sb.AppendLine("| $($row -join ' | ') | $([math]::Round($sum/1MB,1)) |")
}
[void]$sb.AppendLine("| **TOTAL** | $(' | ' * ($langs.Count - 1)) | **$([math]::Round($total/1MB,1))** |")
[void]$sb.AppendLine("")

if (-not $SkipHashes) {
    [void]$sb.AppendLine("## Empreintes sha256 (per file)")
    foreach ($k in $inventory.Keys) { [void]$sb.AppendLine("- $k $($inventory[$k].Hash)") }
}

[System.IO.File]::WriteAllText($ManifestPath, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Host "[package-v2.0.0] manifest written: $ManifestPath ($((Get-Item $ManifestPath).Length) o)"
exit 0